### ISSUE TITLE
Schema 'default' not found

### ISSUE THREAD

**Issue by thaithcock** [aadel/sqlalchemy-solr#9]
Hi there,

I'm running into a problem setting up a chart for my solr collection where it seems to have problems "finding" the default schema:
```
WARNING:superset.connectors.sqla.models:Query SELECT COUNT(*) AS `count`
FROM `default`.mycollection
ORDER BY `count` DESC
LIMIT 100 on schema default failed
Traceback (most recent call last):
  File "/app/superset/connectors/sqla/models.py", line 1863, in query
    df = self.database.get_df(sql, self.schema, mutator=assign_column_label)
  File "/app/superset/models/core.py", line 446, in get_df
    self.db_engine_spec.execute(cursor, sqls[-1])
  File "/app/superset/db_engine_specs/base.py", line 1260, in execute
    raise cls.get_dbapi_mapped_exception(ex)
  File "/app/superset/db_engine_specs/base.py", line 1258, in execute
    cursor.execute(query)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_solr/solrdbapi/_solrdbapi.py", line 72, in func_wrapper
    return func(self, *args, **kwargs)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_solr/solrdbapi/_solrdbapi.py", line 142, in execute
    raise Exception(rows[0]["EXCEPTION"])
Exception: Failed to execute sqlQuery 'SELECT COUNT(*) AS `count`
FROM `default`.mycollection
ORDER BY `count` DESC
LIMIT 100' against JDBC connection 'jdbc:calcitesolr:'.
Caused by: Error while executing SQL "SELECT COUNT(*) AS `count`
FROM `default`.mycollection
ORDER BY `count` DESC
LIMIT 100": From line 2, column 6 to line 2, column 20: Object 'default' not found
```

My understanding is that solr doesn't really have a schema in the same way SQL does so there's only a default option available. I was able to set up and connect the datasource just fine, and the dataset also has no problems, but when I try to create a chart I get this error.

I'm running this through the docker-compose on the repository via the non-dev compose file after setting up the requirements-local.txt.
Am I missing something with my setup? Of course, let me know if there's any more info I can provide.

Thanks!

**Comment by aadel** [comment]
Hi! Could you provide some more information about the environment, such as Python, Solr and Superset versions while I try to regenerate this issue?

**Comment by thaithcock** [comment]
I've forked the main superset repo, I'm just running this from the master branch. I think the latest release is 1.5.1, but there might be some unreleased changes. The dockerfile looks to be using python 3.8.12, and the version of Solr I'm trying to connect to is 8.11.1.

Thanks for responding so quickly, and let me know if you need anything else.

**Comment by thaithcock** [comment]
Hey there! Just wondering if you've made any progress. We've paused working on this while waiting for this issue to be resolved, but are really excited to start introspecting on data we have in our solr cluster. Is there anything I can do to help troubleshoot?

**Comment by aadel** [comment]
Hi! Thank you for following up. I've setup the environment locally but it seems that things have changed a bit on Superset since the latest release of sqlalchemy-solr in terms of third-party drivers integration. I'm actually working to get the library to work with Superset built from `master` (the driver is not recognized/displayed in the drop-down list for some reason when creating a new database) and I'm investigating this issue to resolve it and try to regenerate the `default` schema issue reported here.

**Comment by aadel** [comment]
Hi there!

Changing the query to:
```
SELECT COUNT(*) AS `count`
FROM books
ORDER BY `count` DESC
LIMIT 100
```
just without the `default` schema specifier worked fine with me on Superset docker setup from `master` branch [72e5e57a6](https://github.com/apache/superset/commit/72e5e57a6c04ee222a666a877622e6f983d18ff6):

![Screenshot from 2022-07-08 09-12-42](https://user-images.githubusercontent.com/147645/177937658-aa0327bd-92ac-480e-a330-5f4f76da1db5.png)

However, I encountered two issues while running on the latest Superset:

1. Solr was not recognized when adding a new database until I changed dialect name to `solr` instead of `solrdbapi`

![Screenshot from 2022-07-08 08-55-23](https://user-images.githubusercontent.com/147645/177934739-62c7c604-2fbc-472d-b3dc-f33fcdb2b98a.png)

2. It seems that column reflection in SQL Lab, which I think used to work with previous versions of Superset, is now broken for some reason. It's also related to `default` schema as it returns the following error immediately after loading:

![Screenshot from 2022-07-08 09-04-39](https://user-images.githubusercontent.com/147645/177936178-c2aacc33-f490-4a9a-bf56-acb5274d4078.png)

I'm investigating this issue too.

Charts are also broken with the latest version of Superset I think due to `default` specifier. As a work around, Virtual SQL datasets can be used. For example, the following maps to the query above:

![Screenshot from 2022-07-08 10-08-18](https://user-images.githubusercontent.com/147645/177947541-48008fe7-5d46-4095-b752-372c53a9a90c.png)

and it yields the following chart:

![Screenshot from 2022-07-08 10-10-39](https://user-images.githubusercontent.com/147645/177947771-bb20e532-ff70-424c-ab1a-74d5469b06bb.png)

But this requires some updates to the package as it doesn't currently support Virtual SQL datasets. Therefore, I think the two upcoming features/fixes here are translating SQL schema and supporting Virtual SQL.

**Comment by aadel** [comment]
Yes, that makes sense

**Comment by thaithcock** [comment]
Does #10 cover this?

**Comment by aadel** [comment]
Hey @thaithcock! Yes, #10 covers the two issues above plus any other issues that might arise when upgrading to support Superset 2.0.

**Comment by thaithcock** [comment]
Sorry for the delay, I'll go ahead and close this issue and start tracking that one. Thanks again!
